export const SET_RECORD_PREMISSION = "APP/SET_RECORD_PREMISSION";
export const SET_VOLUME = "PLAYER/SET_VOLUME";
export const SET_IS_MUTED = "PLAYER/SET_IS_MUTED";
export const SET_SOUND_DURATION = "PLAYER/SET_RECORD_PREMISSION";
export const SET_SOUND_POSITION = "PLAYER/SET_SOUND_POSITION";
export const SET_SHOULD_PLAY = "PLAYER/SET_SHOULD_PLAY";
export const SET_SHOULD_PLAY_AT_END_OF_SEEK =
  "PLAYER/SET_SHOULD_PLAY_AT_END_OF_SEEK";
export const SET_IS_LOOPING = "PLAYER/SET_IS_LOOPING";
export const SET_IS_PLAYING = "PLAYER/SET_IS_PLAYING";
export const SET_IS_SEEKING = "PLAYER/SET_IS_SEEKING";
export const SET_RECORD_DURATION = "RECORDER/SET_RECORD_DURATION";
export const SET_IS_RECORDING = "PLAYER/SET_IS_RECORDING";
export const SET_REC_COLOR = "PLAYER/SET_REC_COLOR";
export const SET_IS_PALYBACK_ALLOWED = "PLAYER/SET_IS_PALYBACK_ALLOWED";
export const SET_IS_LOADING = "APP/SET_IS_LOADING";
